POST http://localhost:5173/api/member/signup
Content-Type: application/json

{
  "id": 22,
  "email": "22@22",
  "password": "22",
  "name": "rts",
  "nickname": "22",
  "gender": "male",
  "birth": "2001-06-16",
  "phone": "010-4066-3695",
  "inserted": ""
}
